#spring.output.ansi.enabled=always
#也是关闭启动界面
#spring.main.banner-mode=off
server:
  port: 8081
  servlet:
    session:
      timeout: 30
  tomcat:
    uri-encoding: UTF-8

age: 18
name: lixingzhen

personinfo:
  name: zhujinwei
  age: 2

